### ISSUE TITLE
Azure API Management

### ISSUE THREAD

**Issue by joelhulen** [solliancenet/serverless-microservices#2]
Create service and configure to map to API endpoints provided by Azure Functions

**Comment by iliassays** [comment]
> Ok...based on input from some security experts, we decided to move the validation back into the code. To do this, we created a Utility static method that can be used to validate token:
> 
> ```cs
>         public static async Task ValidateToken(HttpRequest request)
>         {
>             var validationService = ServiceFactory.GetTokenValidationService();
>             if (validationService.AuthEnabled)
>             {
>                 var user = await validationService.AuthenticateRequest(request);
>                 if (user == null)
>                     throw new Exception(Constants.SECURITY_VALITION_ERROR);
>             }
>         }
> ```
> 
> Since filters cannot be used for now, the following is an example of how each HTTP endpoint is protected:
> 
> ```cs
>         [FunctionName("GetDrivers")]
>         public static async Task<IActionResult> GetDrivers([HttpTrigger(AuthorizationLevel.Function, "get", 
>                 Route = "drivers")] HttpRequest req, 
>             ILogger log)
>         {
>             log.LogInformation("GetDrivers triggered....");
> 
>             try
>             {
>                 await Utilities.ValidateToken(req);
>                 var persistenceService = ServiceFactory.GetPersistenceService();
>                 return (ActionResult)new OkObjectResult(await persistenceService.RetrieveDrivers());
>             }
>             catch (Exception e)
>             {
>                 var error = $"GetDrivers failed: {e.Message}";
>                 log.LogError(error);
>                 if (error.Contains(Constants.SECURITY_VALITION_ERROR))
>                     return new StatusCodeResult(401);
>                 else
>                     return new BadRequestObjectResult(error);
>             }
>         }
> ```

**Comment by iliassays** [comment]
@khaledhikmat what was the input of security experts based on which you took moving it to code level.  What was the issue related to <validate-jwt...
