### ISSUE TITLE
Migrate to 2.0.12050-alpha release

### ISSUE THREAD

**Issue by khaledhikmat** [solliancenet/serverless-microservices#20]
Attempted a migration to the latest bits, but getting into some issues with the extensions:
[https://social.msdn.microsoft.com/Forums/en-US/abeb01bc-8a8c-4a17-820f-b25c2b76f825/moving-to-2012050alphahelp-please?forum=AzureFunctions](https://social.msdn.microsoft.com/Forums/en-US/abeb01bc-8a8c-4a17-820f-b25c2b76f825/moving-to-2012050alphahelp-please?forum=AzureFunctions)

Waiting for some direction from one of Azure Functions Program Managers

**Comment by joelhulen** [comment]
Closing this issue since we migrated to the general release of v2 a few months ago, and this problem did not appear.
