### ISSUE TITLE
Security filters for Azure functions

### ISSUE THREAD

**Issue by joelhulen** [solliancenet/serverless-microservices#3]
Currently we have temporary code in place to retrieve the user identity based on the passed in auth token (if exists), and then to retrieve the user account information.

Create a filter to centralize this code (make it DRY)

**Comment by arkiaman** [comment]
@khaledhikmat ~~Throw Exception, not a ValidationException~~
~~That only works when using a custom binding, not when using a function filter~~
Actually this works with `FunctionInvocationFilterAttribute` as well, but you must write a message in the response, otherwise a 500 is issued.
